apply plugin: 'com.android.application'

android {
    compileSdk 34

    defaultConfig {
        applicationId "com.hackercola.af"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}

dependencies {
}
